create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  rule_key text not null,
  subject_key text not null,
  created_at timestamptz not null default now(),
  constraint rate_limit_events_rule_key_check
    check (char_length(rule_key) between 1 and 120),
  constraint rate_limit_events_subject_key_check
    check (char_length(subject_key) between 1 and 240)
);

create index if not exists rate_limit_events_lookup_idx
  on public.rate_limit_events(rule_key, subject_key, created_at);

alter table public.rate_limit_events enable row level security;

revoke all on public.rate_limit_events from anon, authenticated;
grant select, insert, delete on public.rate_limit_events to service_role;

insert into public.rate_limit_events (
  rule_key,
  subject_key,
  created_at
)
select
  counters.rule_key,
  counters.subject_key,
  counters.updated_at
from public.rate_limit_counters as counters
cross join lateral generate_series(1, counters.request_count)
where counters.window_start >= now() - interval '1 day'
on conflict do nothing;

create or replace function public.consume_rate_limit(
  p_rule_key text,
  p_subject_key text,
  p_max_count integer,
  p_window_seconds integer
)
returns table (
  allowed boolean,
  remaining integer,
  reset_at timestamptz,
  limit_count integer
)
language plpgsql
set search_path = public
as $$
declare
  v_window_start timestamptz;
  v_current_count integer;
  v_oldest_event_at timestamptz;
  v_now timestamptz := now();
begin
  if p_rule_key is null or btrim(p_rule_key) = '' then
    raise exception 'INVALID_RATE_LIMIT_RULE';
  end if;

  if p_subject_key is null or btrim(p_subject_key) = '' then
    raise exception 'INVALID_RATE_LIMIT_SUBJECT';
  end if;

  if p_max_count <= 0 or p_window_seconds <= 0 then
    raise exception 'INVALID_RATE_LIMIT_CONFIG';
  end if;

  v_window_start := v_now - make_interval(secs => p_window_seconds);

  perform pg_advisory_xact_lock(
    hashtextextended(p_rule_key || ':' || p_subject_key, 0)
  );

  delete from public.rate_limit_events
  where rule_key = p_rule_key
    and subject_key = p_subject_key
    and created_at < v_window_start;

  select
    count(*)::integer,
    min(created_at)
  into
    v_current_count,
    v_oldest_event_at
  from public.rate_limit_events
  where rule_key = p_rule_key
    and subject_key = p_subject_key
    and created_at >= v_window_start;

  if v_current_count >= p_max_count then
    return query
    select
      false as allowed,
      0 as remaining,
      coalesce(v_oldest_event_at, v_now) + make_interval(secs => p_window_seconds) as reset_at,
      p_max_count as limit_count;
    return;
  end if;

  insert into public.rate_limit_events (
    rule_key,
    subject_key,
    created_at
  )
  values (
    p_rule_key,
    p_subject_key,
    v_now
  );

  return query
  select
    true as allowed,
    greatest(p_max_count - v_current_count - 1, 0) as remaining,
    coalesce(v_oldest_event_at, v_now) + make_interval(secs => p_window_seconds) as reset_at,
    p_max_count as limit_count;
end;
$$;

revoke all on function public.consume_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, text, integer, integer)
  to service_role;
